project:
  matrix:
    image:
      - src/configurator
      - src/documentation

docker-lint: true

file:
  checks:
    cr: []
    crlf: []
    trailing-newline: [
      '.git/', '*.png', '*.jpg', '*.jpeg', '*.ico', '*.svg', 'docs/*.md',
    ]
    trailing-single-newline: [
      '.git/', '*.png', '*.jpg', '*.jpeg', '*.ico', '*.svg', 'docs/*.md',
    ]
    utf8: []
    utf8-bom: []
    trailing-space: [
      '.git/', '*.png', '*.jpg', '*.jpeg', '*.ico', '*.svg', 'docs/*.md',
    ]
  steps:
    Checkmake: dogmatic69/actions/file/lint/checkmake@master
    yaml-lint:
      uses: ibiqlik/action-yamllint@master
      with:
        config_file: .yamllint.yml

git:
  checks:
    - conflicts
    - ignored
  steps:
    'Git Leaks': dogmatic69/actions/git/audit/gitleaks@master

trivy:
  matrix:
    image:
      - docker/audit/trivy
      - docker/lint/hadolint
      - docker/service
      - file/lint/awesome-ci
      - file/lint/checkmake
      - git/audit/gitleaks
      - git/lint/awesome-ci
      - src/documentation
      - src/configurator
