'on':
  pull_request:
    branches: ['master']

docker-lint: true

publish:
  environment: dev
  target: github
  matrix:
    service:
      - src/configurator

project:
  matrix:
    image:
      - src/configurator
      - src/documentation

file:
  checks:
    cr: []
    crlf: []
    trailing-newline: []
    trailing-single-newline: []
    utf8: []
    utf8-bom: []
    trailing-space: []
  steps:
    Checkmake: dogmatic69/actions/file/lint/checkmake@master
    yaml-lint:
      uses: ibiqlik/action-yamllint@master
      with:
        config_file: .yamllint.yml

git:
  checks:
    - conflicts
    - ignored
  steps:
    'Git Leaks': dogmatic69/actions/git/audit/gitleaks@master
    'Commit Lint': dogmatic69/actions/git/lint/commit-lint@master

trivy:
  matrix:
    image:
      - docker/audit/trivy
      - docker/lint/hadolint
      - docker/service
      - file/lint/awesome-ci
      - file/lint/checkmake
      - git/audit/gitleaks
      - git/lint/awesome-ci
      - src/documentation
      - src/configurator
