'on':
  pull_request:
    branches: ['master']

include:
  - _ci.yml

publish:
  environment: dev
  target: github
  matrix:
    service:
      - src/configurator

git:
  steps:
    'Commit Lint': dogmatic69/actions/git/lint/commit-lint@master
