'on':
  pull_request:
    branches: ['master']

include:
  - _ci.yml

publish:
  environment: dev
  target: github
  matrix:
    service:
      - src/configurator

git:
  steps:
    - name: 'Commit Lint'
      uses: dogmatic69/actions/git/lint/commit-lint@master
      with:
        depth: 200
