
on:
  pull_request:
    branches: ['master']

publish: false
project: false
terraform: false

file:
  checks:
    cr: []
    crlf: []
    trailing-newline: []
    trailing-single-newline: []
    utf8: []
    utf8-bom: []
    trailing-space: []
  steps:
    Checkmake: dogmatic69/actions/file/lint/checkmake@master

git:
  checks:
    - conflicts
    - ignored
  steps:
    'Git Leaks': dogmatic69/actions/git/audit/gitleaks@master
    'Commit Lint': dogmatic69/actions/git/lint/commit-lint@master

trivy:
  matrix:
    image:
      - docker/audit/trivy
      - docker/lint/hadolint
      - docker/service
      - file/lint/awesome-ci
      - file/lint/checkmake
      - git/audit/gitleaks
      - git/lint/awesome-ci
      - src/documentation
      - src/configurator
