name: Checkov
description: |
  Checkov is a static code analysis tool for infrastructure-as-code. It scans
  cloud infrastructure provisioned using Terraform and detects security and
  compliance misconfigurations.

  Checkov is written in Python and provides a simple method to write and
  manage policies. It follows the CIS Foundations benchmarks where applicable.

inputs:
  path:
    description: |
      The path to the repository that will be checked. Defaults to the location of `actions/checkout` default path.
    required: false
    default: /github/workspace
runs:
  using: 'docker'
  image: 'Dockerfile'
