name: 'Dockerfile Linter'
description: |
  A smarter Dockerfile linter that helps you build [best practice][] Docker
  images. The linter is parsing the Dockerfile into an AST and performs rules
  on top of the AST. It is standing on the shoulders of [ShellCheck][] to lint
  the Bash code inside `RUN` instructions.

  Adapted from [hadolint/hadolint](https://github.com/hadolint/hadolint)

  [best practice]: https://dockr.ly/3cMOnq4
  [ShellCheck]: https://github.com/koalaman/shellcheck

inputs:
  path:
    description: Path to search for Dockerfiles that will be scanned
    required: false
    default: /github/workspace
  version:
    description: The version of hadolint to be used
    required: false
    default: latest
runs:
  using: 'docker'
  image: 'Dockerfile'
