name: automation triage
'on':
  - pull_request
jobs:
  workflow-check:
    name: Workflow Check
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Git Fetch
        run: |
          git fetch
      - name: Configurator
        run: |
          make -C ${GITHUB_WORKSPACE}/src/configurator run-all
          git status
          git diff-index --quiet HEAD -- || (echo "Changes found"; git diff)
          git diff-index --quiet HEAD --
    runs-on: ubuntu-latest
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
  size-label:
    runs-on: ubuntu-latest
    steps:
      - name: size-label
        uses: pascalgn/size-label-action@master
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
