name: automation triage
'on':
  - pull_request
jobs:
  workflow-check:
    name: Workflow Check
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Configurator
        run: >
          make -C ${GITHUB_WORKSPACE}/src/configurator run-all

          git status

          git diff-index --quiet HEAD -- || echo "Changes found in workflow,
          please update"

          git diff-index --quiet HEAD --
    runs-on: ubuntu-latest
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
