name: ci master
'on':
  push:
    branches:
      - master
jobs:
  project-done:
    name: Project Done
    needs:
      - project-checks
    steps:
      - run: true
    runs-on: ubuntu-latest
  all-done:
    name: All Done
    needs:
      - file-lint
      - git-lint
      - project-done
    steps:
      - run: true
    runs-on: ubuntu-latest
  docker-done:
    name: Docker Done
    needs:
      - audit-trivy
      - dockerfile-lint
    steps:
      - run: true
    runs-on: ubuntu-latest
  workflow-check:
    name: Workflow Check
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Configurator
        run: >
          make -C ${GITHUB_WORKSPACE}/src/configurator run-all

          git status

          git diff-index --quiet HEAD -- || echo "Changes found in workflow,
          please update"

          git diff-index --quiet HEAD --
    runs-on: ubuntu-latest
  file-lint:
    name: File Lint
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: cr
        uses: dogmatic69/actions/file/lint/awesome-ci@master
        with:
          command: file-cr
      - name: crlf
        uses: dogmatic69/actions/file/lint/awesome-ci@master
        with:
          command: file-crlf
      - name: trailing-newline
        uses: dogmatic69/actions/file/lint/awesome-ci@master
        with:
          command: file-trailing-newline
      - name: trailing-single-newline
        uses: dogmatic69/actions/file/lint/awesome-ci@master
        with:
          command: file-trailing-single-newline
      - name: utf8
        uses: dogmatic69/actions/file/lint/awesome-ci@master
        with:
          command: file-utf8
      - name: utf8-bom
        uses: dogmatic69/actions/file/lint/awesome-ci@master
        with:
          command: file-utf8-bom
      - name: trailing-space
        uses: dogmatic69/actions/file/lint/awesome-ci@master
        with:
          command: file-trailing-space
      - name: Checkmake
        uses: dogmatic69/actions/file/lint/checkmake@master
    runs-on: ubuntu-latest
  git-lint:
    name: Git Lint
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Git conflicts
        uses: dogmatic69/actions/git/lint/awesome-ci@master
        with:
          command: git-conflicts
      - name: Git ignored
        uses: dogmatic69/actions/git/lint/awesome-ci@master
        with:
          command: git-ignored
      - name: Git Leaks
        uses: dogmatic69/actions/git/audit/gitleaks@master
    runs-on: ubuntu-latest
  audit-trivy:
    name: Audit Trivy
    strategy:
      matrix:
        image:
          - docker/audit/trivy
          - docker/lint/hadolint
          - docker/service
          - file/lint/awesome-ci
          - file/lint/checkmake
          - git/audit/gitleaks
          - git/lint/awesome-ci
          - src/documentation
          - src/configurator
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Build
        run: |
          docker build -t ${{ matrix.image }} ./${{ matrix.image }}
      - name: 'Trivy Scan ${{ matrix.image }}'
        uses: dogmatic69/actions/docker/audit/trivy@master
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          image: '${{ matrix.image }}'
          path: './${{ matrix.image }}'
    runs-on: ubuntu-latest
  dockerfile-lint:
    name: Dockerfile lint
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Hadolint
        uses: dogmatic69/actions/docker/lint/hadolint@master
    runs-on: ubuntu-latest
  project-checks:
    name: Project Checks
    strategy:
      matrix:
        image:
          - src/configurator
          - src/documentation
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: lint
        run: |
          make -C ${{ matrix.image }} lint
      - name: test
        run: |
          make -C ${{ matrix.image }} test
    runs-on: ubuntu-latest
  publish:
    name: Publish
    needs:
      - all-done
    strategy:
      matrix:
        service:
          - src/configurator
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: fetch
        run: |
          git fetch
      - name: Publish
        run: >
          make -C ${{ matrix.service }} publish DOCKER_USER=${{ github.actor }}
          DOCKER_TOKEN=${{ secrets.GITHUB_TOKEN }} ENVIRONMENT=stage
    runs-on: ubuntu-latest
  update-docs:
    name: Update Documentation
    runs-on: ubuntu-latest
    needs:
      - all-done
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@master
      - name: Build docs
        run: |
          make -C ${GITHUB_WORKSPACE}/src/documentation run
      - name: Commit files
        run: >
          cd ${GITHUB_WORKSPACE}

          git config --local user.email "actions@dogmatic69.com"

          git config --local user.name "Action Bot"

          git add docs || true

          git commit -m "chore: update documentation (auto-generated)" -a ||
          true
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
